### ISSUE TITLE
Show the result of a key

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#10]
Using "click to see fields", (besides it could be a tiny bit more nicely formatted :P ), it would be awesome if it showed the results of the query in the table?
At least, when it's a `limit 1` query?

**Comment by lekoala** [comment]
Hi there,

I changed a bit the formatting for the fields when you click on the row. Instead of using the built in table, I simply show a div.

I'm not sure of the added value of showing the result for a query returning 1 row. It's going to add a lot of stuff that is not very useful most of the time.

However I realised that the showqueries variable tool is a good candidate for a revamp. So I made some changes to show the queries in a nicer way and display their results.

Tell me what you think :-)
