### ISSUE TITLE
Problems with own jquery

### ISSUE THREAD

**Issue by wernerkrauss** [lekoala/silverstripe-debugbar#12]
On my setup i block standard (old) jquery but use my own which i include when rendering the templates.

Unfortunately debugbar wants to inject the javascript before my own jquery is put to requirements, so it's called before and voila - ReferenceError: jQuery is not defined

For now i have to inject my own jquery in Page_Controller::init to get debugbar work, another approach to inject required javascript as late as possible would be great.

Maybe RequestFilter could work? https://docs.silverstripe.org/en/3.3/developer_guides/controllers/requestfilters/

**Comment by lekoala** [comment]
Yes I was aware of this problem... as quoted from the readme

> Please note that jQuery is excluded from vendors and you are expected to include
> your own jQuery version in Page::init().

Request filter are not much of an option, because preRequest is too early and postRequest is too late (the response is already generated). Maybe if I drop the Requirements API and inject things manually inside the response it would be an option.

Currently, I'm including it "onAfterInit" (which is not perfect, for Security page for instance). The problem is that afterCallActionHandler is not always called, so I can't rely on that.

Maybe I'll inject things manually in the response, it might be the easiest solution... is this a big issue to include jquery on init for you? I tend to include it as early as possible in my projects

**Comment by wernerkrauss** [comment]
Well, I like to include my JS in templates, cause it can be easily overwritten there. Unfortunately templates are rendered inside-out, so it happens quite often that something injects in front of my own jquery :(

**Comment by robbieaverill** [comment]
This issue means that this module doesn't work on any page of a vanilla SilverStripe (3.6.0) install.

**Comment by MattyBalaam** [comment]
If it’s too much trouble to rewrite into non-jQuery JavaScript, these days you could probably quite easily use something like webpack to package up the code with it’s own contained jquery module. I can take a look at doing a pull request if it’s likely to be accepted.

**Comment by lekoala** [comment]
I'm using https://github.com/maximebf/php-debugbar so yes, it requires jQuery. The real issue in my opinion is that SilverStripe should provide a way to globally handle how jQuery (and other libs) is installed to avoid copies. It cannot be a requirement from the theme, because so many form fields for instance will require jQuery. I really believe it's just a bad idea to include jQuery in a template (but I can understand it can work ok in some circumstance).

However, we should find a solution so that it works on a fresh install, so any proposal that fixes that is welcome!

**Comment by MattyBalaam** [comment]
I'll see what I can do over the weekend. From my point of view it would be very beneficial, I rarely use jQuery these days so having to add some flags and then loading jQuery when required is a little tedious.

Moving forward it sounds like that in SS4 Webpack is going to be the standard for packaging requirements in the core modules anyway. https://github.com/silverstripe/webpack-config

**Comment by lekoala** [comment]
the debugbar should now working without any configuration on a fresh install (not tested, but since we include the bundled jquery version, it should be ok)
