### ISSUE TITLE
Timeline improvement idea on master branch

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-debugbar#127]
I saw you updated the timeline with more details (yay!) And then a separate table with all the calls made below it.

I think it would be more readable, if the call table was a separate tab? (Although, I must say, the tab bar is getting quite heavily populated!)

**Comment by Firesphere** [comment]
Just a thought, I don't know if it's possible, but is sub-tabs maybe an option, to reduce the crowd on the main bar?

**Comment by lekoala** [comment]
@Firesphere the two tables are from the update to latest version of the assets. But they are a welcome addition. I made a small change in order to aggregate calls to the same label in the timeline because it's much nicer imho.. the templates tab is not super useful anymore because I track templates in the timeline now in order to get an idea of the time spent rendering stuff. Not sure what is the best why to move forward on this as I'm still a bit experimenting with all of this 👍

**Comment by Firesphere** [comment]
Fair enough :) My initial guess, would be using the `templates` tab to put the second table in, and rename it to `timings` or something. I'm not sure either, but I appreciate your work a lot!

**Comment by lekoala** [comment]
well i'm not sure adding another tab is going to help the overall ui.

i'm going to close this, if @Firesphere has a better proposal, i'm happy to revisit this issue
