### ISSUE TITLE
setup github workflow

### ISSUE THREAD

**Issue by lekoala** [lekoala/silverstripe-debugbar#141]
@GuySartorelli I wouldn't mind if you could have a look at how to setup https://github.com/silverstripe/gha-ci for this module :-) it seems it doesn't find the branch, I don't know if the "v" prefix is required or not or if I need to follow some kind of convention for it to work.

## PRs
- https://github.com/lekoala/silverstripe-debugbar/pull/143

**Comment by GuySartorelli** [comment]
I'll add this to the backlog.

**Comment by GuySartorelli** [comment]
The `v*` refers to the tag. We have an auto-tagging system so that whenever we tag, say, 1.2.3, it will also automatically tag `v1` so that `v1` is always the most recent tag. This mimics the `^1` composer syntax.
You'll notice in https://github.com/silverstripe/gha-ci/tags there is no `v2` tag. That's why https://github.com/lekoala/silverstripe-debugbar/blob/master/.github/workflows/ci.yml isn't working. It needs to use a valid tag - in this case `v1`.

I've created https://github.com/lekoala/silverstripe-debugbar/pull/143 to address this.

**Comment by lekoala** [comment]
@GuySartorelli ah great! it's a great piece of software you get there. it's working great :-)

<img width="766" alt="image" src="https://user-images.githubusercontent.com/250762/188164505-2077cdee-bf56-4ede-b472-ea846e341d5f.png">
