### ISSUE TITLE
Requirements require themselves too early

### ISSUE THREAD

**Issue by NightJar** [lekoala/silverstripe-debugbar#150]
https://github.com/lekoala/silverstripe-debugbar/blob/d346a878151152dd6247c0ae2b0c4f270cd20c47/code/Extension/ControllerExtension.php#L35-L40

I have recently spent a day on a goose chase trying to find out why some legacy jQuery code didn't work when I tested in dev - eventually to find out that DebugBar is muddling the binding of some extensions by injecting its version of jQuery before any other - the functionality was fine in test & live modes 🤦 

DebugBar's jQuery is the first requirement on any page due to coming after `init` - most of the codebase requires what it needs when a function is called, not in `init`. I suspect this is the more common case for requirement calls, or at least I think debug bar should not interfere as much as possible in any case.

I think it would be better to move the requirement call to be last - i.e. just before rendering.

Changing the `ControllerExtension` to hook the requirements at `afterCallActionHandler` instead seems best.

`Controller` has a weird dual-logic setup where the order of operations is different for the `index` action (rendering happens before the hook call, as opposed to after it as with `RequestHandler`), so there'd need to be an `index()` method added to the extension as well, so that the requirements call doesn't happen _after_ rendering when there is no `index` on the controller (presumably normal case). This should be safe due to the underlay nature of `Extension`, native methods will be preferred.

https://github.com/silverstripe/silverstripe-framework/blob/c278576996f73cf8be53924c0fe55dff86b5045e/src/Control/Controller.php#L285-L304

There is the DebugBar config `include_jquery: false` - but this is not appropriate in my case at least where some pages don't require jQuery either, and DebugBar then causes JavaScript errors due to operating on `undefined`. And as with the inclusion being too early this also means that mostly the local copy of jQuery is also included _after_ all the dependencies when it does load, which makes them fail anyway and still cause JavaScript errors.

**Comment by lekoala** [comment]
@NightJar hey i can understand the confusion. I think your issue is mostly linked to jquery being included twice. Actually, there is some bit of code that deals with detection. You can always safely disable jquery by using `include_jquery` config
DebugBar's own requirement can be added late that's not an issue

Did I get that correctly?

**Comment by NightJar** [comment]
Yes multiple jQuery inclusions is what casuses the issue. I saw the detection code, but it will fail every time because it runs when there are no other requirements - there is no second jquery at that point.
It also won't detect code in `site.js` that is bundled e.g. via webpack (as `admin` does now). I don't think it should though. This is outside the scope of the issue :)

As above, `include_jquery: false` isn't viable because some (many) pages don't include jquery - especially when considering subsites.

I don't think I'm confused about the issue. I'm suggesting DebugBar's requirement should be added late - at the moment it is the first requirement in the entire site.

Making an issue is sometimes a way for me to not forget to make a PR, perhaps doing this will help us understand each other :)

**Comment by lekoala** [comment]
if you find a better place to add requirements, your are most welcome to make a PR ;-)

**Comment by lekoala** [comment]
@NightJar i've tried with Changing the ControllerExtension to hook the requirements at afterCallActionHandler instead seems best but that doesn't work since it needs to be included before page rendering, which can happen during the action
it cannot happen later than beforeCallActionHandler, which is kinda similar to afterInit
since is also due to the script relying on the requirements api, otherwise i need to drop the requirements api and write the path to the files myself to include it later... this is possible but current use case is limited

i don't often encounter websites where jquery is included or not based on individual action. either it's used globally, or not (most of the time)

**Comment by lekoala** [comment]
@NightJar  i added a way to add jquery later if need be
maybe this can be improved further https://github.com/lekoala/silverstripe-debugbar/commit/4fa0f798d56c10de26af9855257afa50ebc8c9bf

**Comment by lekoala** [comment]
i've also identified that it might get include due to the RootURLController, i'm now checking for an instance of ContentController to be there
should also help with this
closing the issue, feel free to reopen if you have further requirements
