### ISSUE TITLE
Remove CSS file widget.css

### ISSUE THREAD

**Issue by sachajudd** [lekoala/silverstripe-debugbar#97]
I've noticed the widget.css file was added back. We removed it previously because it was overriding the core package and moved everything to our own extension stylesheet. `javascript/sqlqueries/widget.css` 

[Commit](https://github.com/lekoala/silverstripe-debugbar/commit/4d08e8885008450072c3dcd120eef2e0d7a1df20)

**Comment by lekoala** [comment]
it's probably better to keep it since it's part of the default assets of the package. When we will make a clear distinction between the composer assets and the custom styles, it will be necessary to override these styles anyway or ensure they are not loaded through the php code. Removing the css file is not going to help much in the long run in my opinion.

also, it was causing errors because the debugbar tries to load this file (this is how I noticed it was missing).

so my recommendation would be : we keep the file, if it's really problematic, we find a way to prevent the loading, or we override the styles provided in it.

however, I have no idea which styles are really impacted.

**Comment by lekoala** [comment]
i'll just close this since it seems it doesn't have any impact
